Repository Techie-AI/Frontend, pull requests merged in 2024-07, with the labels that each got.

#4 Create flutter.yml
  .github/workflows/flutter.yml
Labels: documentation, enhancement, good first issue

#9 Rohitagr0310 patch 1
  .github/workflows/flutter.yml
  .github/workflows/manual-release.yml
Labels: bug

#19 inital chat ui created
  lib/main.dart
  lib/mybot.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#22 trailling spaces fix
  lib/mybot.dart
Labels: enhancement
